[package]
name = "eth2_wallet_manager"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eth2_wallet = { workspace = true }
lockfile = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
