[package]
name = "timer"
version = "0.2.0"
authors = ["Sigma Prime <contact@sigmaprime.io>"]
edition = "2021"

[dependencies]
beacon_chain = { workspace = true }
slot_clock = { workspace = true }
tokio = { workspace = true }
slog = { workspace = true }
task_executor = { workspace = true }
