[package]
name = "eth2_network_config"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = { workspace = true }

build = "build.rs"

[build-dependencies]
zip = { workspace = true }
eth2_config = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[dependencies]
serde_yaml = { workspace = true }
types = { workspace = true }
ethereum_ssz = { workspace = true }
eth2_config = { workspace = true }
discv5 = { workspace = true }
