[package]
name = "lockfile"
version = "0.1.0"
authors = ["Michael Sproul <michael@sigmaprime.io>"]
edition = "2021"

[dependencies]
fs2 = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
