[package]
name = "eth2_key_derivation"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = { workspace = true }
zeroize = { workspace = true }
num-bigint-dig = { version = "0.6.0", features = ["zeroize"] }
ring = { workspace = true }
bls = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
